### ISSUE TITLE
Assumes SkyrimSE GameRelease

### ISSUE THREAD

**Issue by Noggog** [SteveTownsend/ImmersiveEquipmentMeshGen#17]
https://github.com/SteveTownsend/ImmersiveEquipmentMeshGen/blob/main/ImmersiveEquipmentMeshGen/MeshHandler.cs#LL362C98-L362C109

This line assumes that it's SkyrimSE.  This will cause issues with GOG users which have the ini in a different spot.

You should be able to do this:
```cs
var lookup = new IniPathLookup();
var path = lookup.Get(theGameRelease);
```
There should also be a static entry point, like so:
```cs
var path = Mutagen.Bethesda.Inis.Ini.GetTypicalPath(theGameRelease);
```
But this is currently hidden with a todo to do a design pass on the API to make sure it's proper.  I'll look into that

**Comment by SlavicPotato** [comment]
It should be possible to grab GameRelease at runtime, right?

**Comment by Noggog** [comment]
Yeah, Synthesis' state provides game release, so just needs to be passed along
