### ISSUE TITLE
fix outliers like the new ebony mesh in AE

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/ImmersiveEquipmentMeshGen#2]
[Complex feature request described here](https://github.com/SlavicPotato/ied-dev/issues/1#issuecomment-1016948786)

**Comment by SlavicPotato** [comment]
From one of my posts:

> I could be missing something but I'm pretty sure that's a no. Atleast I didn't have to in the dozens of meshes I converted by hand.

I was missing something, applying the transform seems to be proper workaround for this issue. I've re-enabled it in your source and so far it looks good. Since the transform pos is zero and vertex positions adjusted instead, mirroring seems to produce the correct results.

**Comment by SlavicPotato** [comment]
The war axe straps which were were pointing downwards before are now properly mirrored too, apparently the transform rotations were causing that too.

**Comment by SteveTownsend** [comment]
That's fantastic, I'll update to reinstate that logic later tonight. I
would not have known any of this without porting the AllGUD scripts, I'm no
expert.

**Comment by SteveTownsend** [comment]
fixed in v1.2.0
