### ISSUE TITLE
Meshes aren't picked up by Simple Dual Sheath

### ISSUE THREAD

**Issue by Cloud-and-Proud** [SteveTownsend/ImmersiveEquipmentMeshGen#4]
Hej, I've set up the patcher to output into an MO2 mod:
C:\Modding\MO2\mods\ImmersiveEquipmentMeshGen Output
I've enabled the mod, and checked that there are correct meshes in there, but it doesn't seem to actually do anything in-game...? The straps are still the wrong way around
I've also checked using the scimitar to make sure it's not the skeleton being incorrect

**Comment by Cloud-and-Proud** [comment]
Hej, so, upon further examination, it appears to be a problem specifically with Elsopa's Iron Weapons
[https://www.nexusmods.com/skyrimspecialedition/mods/52605](https://www.nexusmods.com/skyrimspecialedition/mods/52605)
They don't mirror correctly, but the scabbards on my imperial swords do
![20220225155005_1](https://user-images.githubusercontent.com/57964924/155754786-e38fa767-370f-480f-9c36-8bdaee7e39a1.jpg)
![20220225155012_1](https://user-images.githubusercontent.com/57964924/155754788-6537332d-85a6-459f-8fea-f13bfdcc6d8c.jpg)

**Comment by SlavicPotato** [comment]
This is due to that mod having legacy (LE) meshes and the mesh gen doesn't currently handle those properly.  You can use SSE NIF Optimizer to convert the LE meshes to SE.

**Comment by Cloud-and-Proud** [comment]
Woah! Ok, thanks

**Comment by SteveTownsend** [comment]
I'm out of town till Sunday but will catch up on the new issues tomorrow.

**Comment by SteveTownsend** [comment]
this appears to be resolved by migrating the meshes to be SE-compliant
